// Sample data for committee-hub prototype.
// Realistic-ish Indonesian campus org content. Exposed on window so all
// Babel-compiled scripts share scope.

const _today = new Date("2026-05-25");
const _dayMs = 86_400_000;
const _d = (offsetDays) => new Date(_today.getTime() + offsetDays * _dayMs);
const _fmtDate = (d) => d.toISOString().slice(0, 10);
const _fmtDateTime = (d) => d.toISOString().slice(0, 16).replace("T", " ");

const USERS = [
  {
    id: "u-001",
    name: "Arini Wirahadi",
    email: "arini.w@uni.id",
    role: "ketua_panitia",
    image: "AW",
    dept: "Teknik Informatika",
  },
  {
    id: "u-002",
    name: "Bagas Pratama",
    email: "bagas.p@uni.id",
    role: "mahasiswa",
    image: "BP",
    dept: "Sistem Informasi",
  },
  {
    id: "u-003",
    name: "Citra Halim",
    email: "citra.h@uni.id",
    role: "pengurus_ormawa",
    image: "CH",
    dept: "BEM Fakultas Teknik",
  },
  {
    id: "u-004",
    name: "Daffa Nugraha",
    email: "daffa.n@uni.id",
    role: "pihak_fakultas",
    image: "DN",
    dept: "Wakil Dekan III",
  },
  {
    id: "u-005",
    name: "Eka Saraswati",
    email: "eka.s@uni.id",
    role: "pihak_universitas",
    image: "ES",
    dept: "WR III Kemahasiswaan",
  },
  {
    id: "u-006",
    name: "Fadhil Iskandar",
    email: "fadhil.i@uni.id",
    role: "admin_sistem",
    image: "FI",
    dept: "PSTI",
  },
  {
    id: "u-007",
    name: "Galang Pradipta",
    email: "galang.p@uni.id",
    role: "mahasiswa",
    image: "GP",
    dept: "Teknik Elektro",
  },
  {
    id: "u-008",
    name: "Hana Maharani",
    email: "hana.m@uni.id",
    role: "mahasiswa",
    image: "HM",
    dept: "Desain Komunikasi Visual",
  },
  {
    id: "u-009",
    name: "Ivan Setiawan",
    email: "ivan.s@uni.id",
    role: "mahasiswa",
    image: "IS",
    dept: "Manajemen",
  },
  {
    id: "u-010",
    name: "Jelita Rahmadani",
    email: "jelita.r@uni.id",
    role: "mahasiswa",
    image: "JR",
    dept: "Akuntansi",
  },
  {
    id: "u-011",
    name: "Krisna Wibawa",
    email: "krisna.w@uni.id",
    role: "ketua_panitia",
    image: "KW",
    dept: "Hubungan Internasional",
  },
  {
    id: "u-012",
    name: "Laras Anindya",
    email: "laras.a@uni.id",
    role: "mahasiswa",
    image: "LA",
    dept: "Psikologi",
  },
  {
    id: "u-013",
    name: "Mahesa Putra",
    email: "mahesa.p@uni.id",
    role: "mahasiswa",
    image: "MP",
    dept: "Ilmu Komunikasi",
  },
  {
    id: "u-014",
    name: "Nadya Kusuma",
    email: "nadya.k@uni.id",
    role: "mahasiswa",
    image: "NK",
    dept: "Arsitektur",
  },
  {
    id: "u-015",
    name: "Oscar Tjandra",
    email: "oscar.t@uni.id",
    role: "mahasiswa",
    image: "OT",
    dept: "Teknik Industri",
  },
];

const ROLE_LABELS = {
  mahasiswa: "Mahasiswa",
  ketua_panitia: "Ketua Panitia",
  pengurus_ormawa: "Pengurus Ormawa",
  pihak_fakultas: "Pihak Fakultas",
  pihak_universitas: "Pihak Universitas",
  admin_sistem: "Admin Sistem",
};

const EVENTS = [
  {
    id: "e-2041",
    name: "TechFest 2026: AI for Campus",
    description:
      "Two-day tech conference, hands-on workshops on agentic AI tools, and a hackathon final.",
    date: _fmtDate(_d(18)),
    location: "Auditorium FT, Gedung G",
    quota: 480,
    type: "external",
    status: "open",
    createdById: "u-001",
    createdAt: _fmtDate(_d(-22)),
  },
  {
    id: "e-2042",
    name: "Orientasi Mahasiswa Baru 2026",
    description:
      "Universitas-wide orientation, mentor pairing, and faculty fair.",
    date: _fmtDate(_d(45)),
    location: "Lapangan Utama",
    quota: 1800,
    type: "external",
    status: "draft",
    createdById: "u-011",
    createdAt: _fmtDate(_d(-9)),
  },
  {
    id: "e-2043",
    name: "Workshop UI/UX Fundamentals",
    description:
      "Three-session intensive with industry mentors. Project-based.",
    date: _fmtDate(_d(7)),
    location: "Lab Multimedia 3.04",
    quota: 60,
    type: "internal",
    status: "open",
    createdById: "u-001",
    createdAt: _fmtDate(_d(-30)),
  },
  {
    id: "e-2044",
    name: "Inter-faculty Futsal League",
    description:
      "Six-week round-robin between faculty teams. Includes opening ceremony.",
    date: _fmtDate(_d(12)),
    location: "GOR Mahasiswa",
    quota: 240,
    type: "external",
    status: "open",
    createdById: "u-011",
    createdAt: _fmtDate(_d(-40)),
  },
  {
    id: "e-2045",
    name: "Career Day: Engineering Track",
    description:
      "Talks with alumni at Gojek, Tokopedia, and Telkom. Resume clinic in afternoon.",
    date: _fmtDate(_d(-6)),
    location: "Aula Pasca, Lt. 7",
    quota: 320,
    type: "external",
    status: "closed",
    createdById: "u-001",
    createdAt: _fmtDate(_d(-55)),
  },
  {
    id: "e-2046",
    name: "Hackathon Internal: HCI 2026",
    description: "Closed event for HCI students. 24-hour build sprint.",
    date: _fmtDate(_d(3)),
    location: "Lab Komputer 2.11",
    quota: 48,
    type: "internal",
    status: "open",
    createdById: "u-001",
    createdAt: _fmtDate(_d(-14)),
  },
  {
    id: "e-2047",
    name: "Seminar Kewirausahaan Mahasiswa",
    description:
      "Founder stories from campus startups. Lightning talks + panel.",
    date: _fmtDate(_d(21)),
    location: "Ruang Seminar A.301",
    quota: 180,
    type: "external",
    status: "draft",
    createdById: "u-011",
    createdAt: _fmtDate(_d(-4)),
  },
  {
    id: "e-2048",
    name: "Donor Darah Mahasiswa Mei",
    description:
      "Bekerja sama dengan PMI kota. Open untuk semua mahasiswa & staf.",
    date: _fmtDate(_d(-12)),
    location: "Lobby Rektorat",
    quota: 200,
    type: "external",
    status: "closed",
    createdById: "u-001",
    createdAt: _fmtDate(_d(-60)),
  },
];

const PROPOSALS = [
  {
    id: "p-501",
    eventId: "e-2041",
    submittedById: "u-001",
    title: "TechFest 2026 — Universitas-scale proposal",
    scope: "universitas",
    status: "pending",
    submissionRound: 2,
    submittedAt: _fmtDateTime(_d(-2)),
    documentUrl: "/docs/techfest-2026-v2.pdf",
  },
  {
    id: "p-502",
    eventId: "e-2042",
    submittedById: "u-011",
    title: "Orientasi Mahasiswa Baru 2026",
    scope: "universitas",
    status: "revision_requested",
    submissionRound: 1,
    submittedAt: _fmtDateTime(_d(-5)),
    documentUrl: "/docs/ospek-2026.pdf",
  },
  {
    id: "p-503",
    eventId: "e-2043",
    submittedById: "u-001",
    title: "Workshop UI/UX Fundamentals",
    scope: "fakultas",
    status: "approved",
    submissionRound: 1,
    submittedAt: _fmtDateTime(_d(-25)),
    documentUrl: "/docs/uiux-workshop.pdf",
  },
  {
    id: "p-504",
    eventId: "e-2044",
    submittedById: "u-011",
    title: "Liga Futsal Antar-Fakultas",
    scope: "fakultas",
    status: "approved",
    submissionRound: 2,
    submittedAt: _fmtDateTime(_d(-32)),
    documentUrl: "/docs/futsal-league.pdf",
  },
  {
    id: "p-505",
    eventId: "e-2046",
    submittedById: "u-001",
    title: "Hackathon Internal HCI 2026",
    scope: "ormawa",
    status: "approved",
    submissionRound: 1,
    submittedAt: _fmtDateTime(_d(-10)),
    documentUrl: "/docs/hack-hci.pdf",
  },
  {
    id: "p-506",
    eventId: "e-2047",
    submittedById: "u-011",
    title: "Seminar Kewirausahaan Mahasiswa",
    scope: "ormawa",
    status: "pending",
    submissionRound: 1,
    submittedAt: _fmtDateTime(_d(-1)),
    documentUrl: "/docs/seminar-wirausaha.pdf",
  },
  {
    id: "p-507",
    eventId: "e-2045",
    submittedById: "u-001",
    title: "Career Day — Engineering Track",
    scope: "fakultas",
    status: "approved",
    submissionRound: 1,
    submittedAt: _fmtDateTime(_d(-50)),
    documentUrl: "/docs/career-day.pdf",
  },
  {
    id: "p-508",
    eventId: "e-2048",
    submittedById: "u-001",
    title: "Donor Darah Mei — kolaborasi PMI",
    scope: "ormawa",
    status: "rejected",
    submissionRound: 1,
    submittedAt: _fmtDateTime(_d(-58)),
    documentUrl: "/docs/donor-mei.pdf",
  },
];

const APPROVALS = [
  {
    id: "a-1",
    proposalId: "p-501",
    reviewerId: "u-003",
    level: "ormawa",
    decision: "approved",
    notes: "Anggaran wajar, kapasitas sesuai.",
    submissionRound: 2,
    createdAt: _fmtDateTime(_d(-2)),
  },
  {
    id: "a-2",
    proposalId: "p-501",
    reviewerId: "u-004",
    level: "fakultas",
    decision: "approved",
    notes: "Sudah ditinjau bersama WD III.",
    submissionRound: 2,
    createdAt: _fmtDateTime(_d(-1)),
  },
  {
    id: "a-3",
    proposalId: "p-502",
    reviewerId: "u-003",
    level: "ormawa",
    decision: "revision_requested",
    notes: "Revisi: detail rundown hari ke-2 dan PIC.",
    submissionRound: 1,
    createdAt: _fmtDateTime(_d(-3)),
  },
  {
    id: "a-4",
    proposalId: "p-503",
    reviewerId: "u-003",
    level: "ormawa",
    decision: "approved",
    notes: "OK.",
    submissionRound: 1,
    createdAt: _fmtDateTime(_d(-23)),
  },
  {
    id: "a-5",
    proposalId: "p-503",
    reviewerId: "u-004",
    level: "fakultas",
    decision: "approved",
    notes: "Disetujui.",
    submissionRound: 1,
    createdAt: _fmtDateTime(_d(-21)),
  },
  {
    id: "a-6",
    proposalId: "p-508",
    reviewerId: "u-003",
    level: "ormawa",
    decision: "rejected",
    notes: "Tanggal bentrok dengan UTS.",
    submissionRound: 1,
    createdAt: _fmtDateTime(_d(-56)),
  },
];

const DIVISIONS = [
  {
    id: "d-1",
    eventId: "e-2041",
    name: "Acara",
    description: "Rundown, MC, dan teknis panggung.",
    quota: 8,
    createdAt: _fmtDate(_d(-21)),
  },
  {
    id: "d-2",
    eventId: "e-2041",
    name: "Konsumsi",
    description: "Pengadaan dan distribusi konsumsi peserta + tamu.",
    quota: 5,
    createdAt: _fmtDate(_d(-21)),
  },
  {
    id: "d-3",
    eventId: "e-2041",
    name: "Publikasi",
    description: "Sosial media, poster, dan dokumentasi visual.",
    quota: 6,
    createdAt: _fmtDate(_d(-20)),
  },
  {
    id: "d-4",
    eventId: "e-2041",
    name: "Sponsorship",
    description: "Akuisisi sponsor, partnership, dan media partner.",
    quota: 4,
    createdAt: _fmtDate(_d(-20)),
  },
  {
    id: "d-5",
    eventId: "e-2041",
    name: "Perlengkapan",
    description: "Set up venue, sound system, signage.",
    quota: 6,
    createdAt: _fmtDate(_d(-19)),
  },
  {
    id: "d-6",
    eventId: "e-2043",
    name: "Acara",
    description: "Modul workshop dan koordinasi mentor.",
    quota: 4,
    createdAt: _fmtDate(_d(-28)),
  },
  {
    id: "d-7",
    eventId: "e-2043",
    name: "Publikasi",
    description: "Rekrutmen peserta dan dokumentasi sesi.",
    quota: 3,
    createdAt: _fmtDate(_d(-28)),
  },
  {
    id: "d-8",
    eventId: "e-2044",
    name: "Acara",
    description: "Penjadwalan, wasit, dan opening.",
    quota: 6,
    createdAt: _fmtDate(_d(-38)),
  },
  {
    id: "d-9",
    eventId: "e-2044",
    name: "Konsumsi",
    description: "Konsumsi peserta dan official tiap match-day.",
    quota: 4,
    createdAt: _fmtDate(_d(-37)),
  },
];

const APPLICATIONS = [
  {
    id: "app-1",
    divisionId: "d-1",
    userId: "u-002",
    status: "pending",
    motivation:
      "Saya pernah jadi LO di OSPEK tahun lalu dan tertarik di stage management.",
    createdAt: _fmtDateTime(_d(-3)),
  },
  {
    id: "app-2",
    divisionId: "d-1",
    userId: "u-007",
    status: "pending",
    motivation:
      "Punya pengalaman menyusun rundown event musik kampus, ingin belajar skala lebih besar.",
    createdAt: _fmtDateTime(_d(-2)),
  },
  {
    id: "app-3",
    divisionId: "d-1",
    userId: "u-008",
    status: "accepted",
    motivation: "Tertarik koordinasi tim acara skala konferensi.",
    createdAt: _fmtDateTime(_d(-7)),
  },
  {
    id: "app-4",
    divisionId: "d-2",
    userId: "u-009",
    status: "accepted",
    motivation:
      "Punya kontak vendor catering kampus dan pengalaman event 300+ pax.",
    createdAt: _fmtDateTime(_d(-6)),
  },
  {
    id: "app-5",
    divisionId: "d-2",
    userId: "u-010",
    status: "pending",
    motivation: "Belum pernah jadi panitia, ingin coba dan belajar.",
    createdAt: _fmtDateTime(_d(-1)),
  },
  {
    id: "app-6",
    divisionId: "d-3",
    userId: "u-013",
    status: "accepted",
    motivation: "Aktif di majalah kampus, ingin handle social copy & visual.",
    createdAt: _fmtDateTime(_d(-9)),
  },
  {
    id: "app-7",
    divisionId: "d-3",
    userId: "u-014",
    status: "pending",
    motivation: "Mahasiswa Arsitektur, kuat di poster design dan layouting.",
    createdAt: _fmtDateTime(_d(-4)),
  },
  {
    id: "app-8",
    divisionId: "d-3",
    userId: "u-012",
    status: "rejected",
    motivation: "Ingin nambah pengalaman.",
    createdAt: _fmtDateTime(_d(-8)),
  },
  {
    id: "app-9",
    divisionId: "d-4",
    userId: "u-015",
    status: "accepted",
    motivation:
      "Magang di tim BD startup, terbiasa kirim cold outreach ke sponsor.",
    createdAt: _fmtDateTime(_d(-10)),
  },
  {
    id: "app-10",
    divisionId: "d-5",
    userId: "u-002",
    status: "pending",
    motivation: "Tertarik di teknis venue & sound.",
    createdAt: _fmtDateTime(_d(-2)),
  },
];

const NOTIFICATIONS = [
  {
    id: "n-1",
    userId: "u-001",
    type: "proposal_approved",
    message: 'Proposal "TechFest 2026" approved at Fakultas level.',
    referenceType: "proposal",
    referenceId: "p-501",
    read: false,
    createdAt: _fmtDateTime(_d(-1)),
  },
  {
    id: "n-2",
    userId: "u-001",
    type: "application_accepted",
    message: "You accepted Hana Maharani for Acara — TechFest 2026.",
    referenceType: "application",
    referenceId: "app-3",
    read: false,
    createdAt: _fmtDateTime(_d(-1)),
  },
  {
    id: "n-3",
    userId: "u-001",
    type: "registration_success",
    message: "24 new registrations on Workshop UI/UX Fundamentals.",
    referenceType: "event",
    referenceId: "e-2043",
    read: false,
    createdAt: _fmtDateTime(_d(-1)),
  },
  {
    id: "n-4",
    userId: "u-001",
    type: "proposal_revision_requested",
    message: "Orientasi 2026 — Ormawa requested revision on rundown day 2.",
    referenceType: "proposal",
    referenceId: "p-502",
    read: true,
    createdAt: _fmtDateTime(_d(-3)),
  },
  {
    id: "n-5",
    userId: "u-001",
    type: "application_accepted",
    message: "Ivan Setiawan accepted for Sponsorship — TechFest 2026.",
    referenceType: "application",
    referenceId: "app-9",
    read: true,
    createdAt: _fmtDateTime(_d(-5)),
  },
  {
    id: "n-6",
    userId: "u-001",
    type: "proposal_approved",
    message: "Workshop UI/UX Fundamentals — Fakultas approved.",
    referenceType: "proposal",
    referenceId: "p-503",
    read: true,
    createdAt: _fmtDateTime(_d(-21)),
  },
  {
    id: "n-7",
    userId: "u-001",
    type: "proposal_rejected",
    message: "Donor Darah Mei — Ormawa rejected (tanggal bentrok UTS).",
    referenceType: "proposal",
    referenceId: "p-508",
    read: true,
    createdAt: _fmtDateTime(_d(-56)),
  },
  {
    id: "n-8",
    userId: "u-001",
    type: "application_rejected",
    message: "Laras Anindya rejected from Publikasi — TechFest 2026.",
    referenceType: "application",
    referenceId: "app-8",
    read: true,
    createdAt: _fmtDateTime(_d(-8)),
  },
];

const SYSTEM_CONFIG = [
  {
    id: "cfg-1",
    key: "event.default_quota",
    value: "100",
    valueType: "number",
    description: "Default quota for newly created events.",
    updatedById: "u-006",
    updatedAt: _fmtDateTime(_d(-30)),
  },
  {
    id: "cfg-2",
    key: "proposal.review_sla_days",
    value: "3",
    valueType: "number",
    description: "Target SLA (days) for each approval level.",
    updatedById: "u-006",
    updatedAt: _fmtDateTime(_d(-12)),
  },
  {
    id: "cfg-3",
    key: "ticket.code_prefix",
    value: "CMTHB-",
    valueType: "string",
    description: "Prefix used when generating ticket codes.",
    updatedById: "u-006",
    updatedAt: _fmtDateTime(_d(-90)),
  },
  {
    id: "cfg-4",
    key: "notifications.email_relay",
    value: "true",
    valueType: "boolean",
    description: "Mirror in-app notifications to email.",
    updatedById: "u-006",
    updatedAt: _fmtDateTime(_d(-2)),
  },
  {
    id: "cfg-5",
    key: "auth.allowed_domain",
    value: "uni.id",
    valueType: "string",
    description: "Restrict Google sign-in to this email domain.",
    updatedById: "u-006",
    updatedAt: _fmtDateTime(_d(-180)),
  },
];

const ACTIVITY = [
  {
    id: "act-1",
    at: _fmtDateTime(_d(0)),
    who: "u-001",
    verb: "approved committee application",
    target: "Hana Maharani → Acara (TechFest 2026)",
  },
  {
    id: "act-2",
    at: _fmtDateTime(_d(-1)),
    who: "u-004",
    verb: "approved proposal",
    target: "TechFest 2026 — Fakultas round 2",
  },
  {
    id: "act-3",
    at: _fmtDateTime(_d(-1)),
    who: "u-011",
    verb: "submitted proposal",
    target: "Seminar Kewirausahaan Mahasiswa",
  },
  {
    id: "act-4",
    at: _fmtDateTime(_d(-2)),
    who: "u-001",
    verb: "resubmitted proposal",
    target: "TechFest 2026 — round 2",
  },
  {
    id: "act-5",
    at: _fmtDateTime(_d(-2)),
    who: "u-006",
    verb: "updated system config",
    target: "notifications.email_relay = true",
  },
  {
    id: "act-6",
    at: _fmtDateTime(_d(-3)),
    who: "u-003",
    verb: "requested revision",
    target: "Orientasi Mahasiswa Baru 2026",
  },
  {
    id: "act-7",
    at: _fmtDateTime(_d(-4)),
    who: "u-001",
    verb: "created division",
    target: "Perlengkapan — TechFest 2026",
  },
  {
    id: "act-8",
    at: _fmtDateTime(_d(-5)),
    who: "u-011",
    verb: "created event",
    target: "Orientasi Mahasiswa Baru 2026 (draft)",
  },
];

window.DATA = {
  USERS,
  ROLE_LABELS,
  EVENTS,
  PROPOSALS,
  APPROVALS,
  DIVISIONS,
  APPLICATIONS,
  NOTIFICATIONS,
  SYSTEM_CONFIG,
  ACTIVITY,
  today: _today,
  fmtDate: _fmtDate,
  fmtDateTime: _fmtDateTime,
  d: _d,
};
