/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardProposalsRouteImport } from './routes/dashboard/proposals'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardEventsRouteImport } from './routes/dashboard/events'
import { Route as DashboardCommitteeRouteImport } from './routes/dashboard/committee'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProposalsRoute = DashboardProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCommitteeRoute = DashboardCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/committee': typeof DashboardCommitteeRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/committee': typeof DashboardCommitteeRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/committee': typeof DashboardCommitteeRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/committee'
    | '/dashboard/events'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/dashboard/proposals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/committee'
    | '/dashboard/events'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/dashboard/proposals'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/committee'
    | '/dashboard/events'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/dashboard/proposals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/proposals': {
      id: '/dashboard/proposals'
      path: '/proposals'
      fullPath: '/dashboard/proposals'
      preLoaderRoute: typeof DashboardProposalsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/committee': {
      id: '/dashboard/committee'
      path: '/committee'
      fullPath: '/dashboard/committee'
      preLoaderRoute: typeof DashboardCommitteeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardCommitteeRoute: typeof DashboardCommitteeRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardProposalsRoute: typeof DashboardProposalsRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardCommitteeRoute: DashboardCommitteeRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardProposalsRoute: DashboardProposalsRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
